{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "En este laboratorio pondremos en práctica algunos de los conceptos que hemos aprendido en los últimos días.\n",
    "\n",
    "`NOTA: En este laboratorio deberías intentar escribir todas las funciones por ti mismo utilizando solo la sintaxis más básica de Python y sin funciones como len, count, sum, max, min, in, etc. Dale una oportunidad. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "La celda después de cada ejercicio contiene algunas pruebas para verificar si tu función funciona como se espera."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Escribe una función que devuelva el mayor de dos números"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greater(a,b):\n",
    "#tu código aquí\n",
    "    if a > b:\n",
    "        max = a\n",
    "    else:\n",
    "        max = b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 361 : Should be 361\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 980 : Should be 980\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 454 : Should be 454\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 506 : Should be 506\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 979 : Should be 979\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -418 : Should be -418\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 701 : Should be 701\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -723 : Should be -723\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 970 : Should be 970\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 204 : Should be 204\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 418 : Should be 418\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -41 : Should be -41\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 164 : Should be 164\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 750 : Should be 750\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 857 : Should be 857\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 915 : Should be 915\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 344 : Should be 344\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 451 : Should be 451\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 210 : Should be 210\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 369 : Should be 369\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 145 : Should be 145\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 848 : Should be 848\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 591 : Should be 591\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -384 : Should be -384\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 891 : Should be 891\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 541 : Should be 541\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -227 : Should be -227\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 861 : Should be 861\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 737 : Should be 737\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 35 : Should be 35\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 824 : Should be 824\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 952 : Should be 952\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -373 : Should be -373\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 839 : Should be 839\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 912 : Should be 912\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 311 : Should be 311\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 820 : Should be 820\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 960 : Should be 960\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 676 : Should be 676\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 184 : Should be 184\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 136 : Should be 136\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 712 : Should be 712\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 987 : Should be 987\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -538 : Should be -538\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 121 : Should be 121\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 440 : Should be 440\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 670 : Should be 670\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 878 : Should be 878\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 417 : Should be 417\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 763 : Should be 763\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 464 : Should be 464\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 110 : Should be 110\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -111 : Should be -111\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 1 : Should be 1\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -89 : Should be -89\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 165 : Should be 165\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 958 : Should be 958\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -454 : Should be -454\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 957 : Should be 957\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 458 : Should be 458\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 111 : Should be 111\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -51 : Should be -51\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 531 : Should be 531\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 299 : Should be 299\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 485 : Should be 485\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 801 : Should be 801\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 791 : Should be 791\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 657 : Should be 657\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -497 : Should be -497\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 430 : Should be 430\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -497 : Should be -497\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 572 : Should be 572\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -20 : Should be -20\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 940 : Should be 940\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 322 : Should be 322\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 94 : Should be 94\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 506 : Should be 506\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 760 : Should be 760\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -421 : Should be -421\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -12 : Should be -12\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 411 : Should be 411\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -488 : Should be -488\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 735 : Should be 735\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -601 : Should be -601\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 990 : Should be 990\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 653 : Should be 653\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 551 : Should be 551\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 765 : Should be 765\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 525 : Should be 525\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 179 : Should be 179\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -632 : Should be -632\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 676 : Should be 676\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 30 : Should be 30\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -295 : Should be -295\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 951 : Should be 951\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -12 : Should be -12\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 984 : Should be 984\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -189 : Should be -189\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 863 : Should be 863\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\david\\OneDrive\\Ironhack\\ds-consorci-notebooks\\Sessions\\07 - Session VI Python Fundamentals\\lab-functions-es-main\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 636 : Should be 636\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.062s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función\n",
    "max = 0\n",
    "a = int(input(\"Ingrese su primer numero\"))\n",
    "b =  int(input(\"Ingrese su segundo numero\"))\n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Ahora escribe una función que devuelva el elemento más"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Escribe una función que sume todos los elementos de una lista"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_all(lst):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Escribe otra función que multiplique todos los elementos de una lista"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mult_all(lst):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Ahora combina esas dos ideas y escribe una función que reciba una lista y ya sea \"+\" o \"*\", y produzca el resultado acorde"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def oper_all(arr, oper = \"*\"):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Escribe una función que devuelva el factorial de un número."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def factorial(n):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Fórmula factorial\n",
    "# n! = n * (n - 1) *...*1\n",
    "\n",
    "# Este código define una función llamada \"factorial\" que toma una entrada \"n\". La función utiliza un bucle for para iterar a través del rango de números\n",
    "# desde 1 hasta n+1. Para cada número en ese rango, multiplica el valor actual de x por el número en el rango. Al final del bucle,\n",
    "# la función devuelve el valor final de x, que será el factorial del número de entrada \"n\".\n",
    "\n",
    "# El factorial de un entero positivo n es el producto de todos los enteros positivos menores o iguales a n.\n",
    "# Por ejemplo, el factorial de 6 (escrito \"6!\") es 6 * 5 * 4 * 3 * 2 * 1 = 720.\n",
    "\n",
    "# Así que esta función toma una entrada de cualquier entero positivo y devuelve el factorial de ese número."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Escribe una función que tome una lista y devuelva una lista de los valores únicos.\n",
    "\n",
    "`NOTE: No podemos usar set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def unique(lst_un):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Escribe una función que devuelva la moda de una lista, es decir: el elemento que aparece más veces.\n",
    "\n",
    "`NOTE: No se debe usar count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mode_counter(arr):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Escribe una función que calcule la desviación estándar de una lista.\n",
    "`NOTE: no utilices librerías ni ninguna función ya construida. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def st_dev(list_sd):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Escribe una función para verificar si una cadena es un pangrama, es decir: si contiene todas las letras del alfabeto al menos una vez. Ten en cuenta que las cadenas pueden contener caracteres que no son letras."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pangram(string):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Escribe una función que reciba una cadena de palabras separadas por comas y devuelva una cadena de palabras separadas por comas ordenadas alfabéticamente.\n",
    "\n",
    "`NOTA: Puedes usar sorted pero no split y definitivamente no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sort_alpha(string):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Escribe una función para verificar si una contraseña dada es fuerte (al menos 8 caracteres, al menos una minúscula, al menos una mayúscula, al menos un número y al menos un carácter especial). Debería devolver True si es fuerte y False si no lo es."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(password):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_pass(check_pass)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  },
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
